text_ads_loc = "//div[contains(text(),'Text Ads')]"
next_button_loc = "//button[contains(text(),'Next')]"
url_loc = "//input[contains(@name, 'url')]"
display_url_loc = "//input[contains(@name, 'displayUrl')]"
headline_loc = "//input[contains(@name, 'headline')]"
description_loc = "//input[contains(@name, 'description')]"
geolocation_loc = "svg.accordion-carret--N1tss"
birmingham_loc = "//div[contains(text(), 'Birmingham')]"
escort_category_loc = "//div[contains(text(),'Escorts')]"
cpc_loc = "//input[contains(@name,'cpc')]"
daily_loc = "//input[contains(@name,'daily')]"
finish_button_loc = "//button[contains(text(),'Finish')]"

image_ads_loc = "//div[contains(text(),'Image Promotions')]"
phone_number_loc = "//input[contains(@class, 'form-control')]"
choose_profile_card_loc = "//img[contains(@alt,'avatar')]"
choose_photo_loc = "//div[contains(@class, 'thumbnail')]"
checkout_button_loc = "//button[contains(text(), 'Checkout')]"

url_ads_loc = "//div[contains(text(), 'URL Promotions')]"
url_url_loc = "//input[contains(@placeholder, 'Enter your URL') and contains(@tabindex, '1')]"
shemale_category_loc = "//input[contains(@type, 'checkbox') and contains(@data-name, 'Shemale Escorts')]"
cpc_url_loc = "//input[contains(@data-summary-label, 'CPC Bid price')]"
daily_url_loc = "//input[contains(@data-summary-label, 'Daily Budget')]"
